### ISSUE TITLE
TypeError: ReconnectingWebSocket is not a constructor in browser

### ISSUE THREAD

**Issue by Aayush04** [pladaria/reconnecting-websocket#101]
I am unable to instantiate ReconnectingWebSocket when running through the browser after the version 3.2.2.
Before the version 3.2.2 and equal everything was working fine. But now I am getting the following error :
```
client.ts:13 Uncaught TypeError: ReconnectingWebSocket is not a constructor
    at Object.<anonymous> (client.ts:13)
    at __webpack_require__ (bootstrap a23e24d7998736253177:19)
    at Object.<anonymous> (main.ts:9)
    at __webpack_require__ (bootstrap a23e24d7998736253177:19)
    at bootstrap a23e24d7998736253177:62
    at bootstrap a23e24d7998736253177:62
```

My client.ts code is :

```
import { listen } from 'vscode-ws-jsonrpc';
const ReconnectingWebSocket = require ('reconnecting-websocket');

const socketOptions = {
    WebSocket: undefined,
    maxReconnectionDelay: 10000,
    minReconnectionDelay: 1000,
    reconnectionDelayGrowFactor: 1.3,
    connectionTimeout: 10000,
    maxRetries: Infinity,
    debug: false
};
const webSocket = new ReconnectingWebSocket('ws://localhost:3000/', undefined, socketOptions);

listen({
    webSocket,
    onConnection: connection => {
        console.log('connected');
    }
});
```
I checked #95 , but `"esModuleInterop": true` does not worked for me. 

Here is my tsconfig.json:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "declarationMap": true,
        "inlineSources": false,
        "declaration": true,
        "stripInternal": true,
        "lib": [
          "es6",
          "dom"
        ],
        "strict": true,
        "noImplicitReturns": true,
        "noUnusedLocals": true,
        "rootDir": "src",
        "outDir": "lib",
        "baseUrl": ".",
        "skipLibCheck": true,
        "alwaysStrict": true,
        "esModuleInterop": true
    },
    "include": [
    "src"
    ]
}

```

One more thing, running the same client.ts code from terminal `node lib/client.js` working fine. But the same is giving an error in the browser. While debugging in browser console `typeof ReconnectingWebSocket` shows that it's an object but not a function. But `typeof ReconnectingWebSocket.default` giving as function.

So, I use ReconnectingWebSocket with `default` keyword as as 
```
const webSocket = new ReconnectingWebSocket('ws://localhost:3000/', undefined, socketOptions).default;
```
It is now working fine in the browser. But then the same giving the same error when running from terminal. 

Please help how to use ReconnectingWebSocket after the version 3.2.2 ?

**Comment by SantanderAuhAuh** [comment]
Hi, man, have you already solve this problem? I just met the same.It will be so generous if you tell me the answer.Thank you.

**Comment by cgarrovillo** [comment]
This is still an issue at 4.4.0. This project looks abandoned at this point
