### ISSUE TITLE
Event type mismatch using addEventListener and onerror

### ISSUE THREAD

**Issue by kai670** [pladaria/reconnecting-websocket#104]
When using the `addEventListener`/`removeEventListener` methods to listen for error events, the event parameter is expected to be of type `ErrorEvent`. See https://github.com/pladaria/reconnecting-websocket/blob/master/events.ts#L37

```typescript
export interface WebSocketEventListenerMap {
    close: (event: CloseEvent) => void | {handleEvent: (event: CloseEvent) => void};
    error: (event: ErrorEvent) => void | {handleEvent: (event: ErrorEvent) => void};
    message: (event: MessageEvent) => void | {handleEvent: (event: MessageEvent) => void};
    open: (event: Event) => void | {handleEvent: (event: Event) => void};
}
```

However, when using the `.onerror` property the event is expected to be of type `Event`. See https://github.com/pladaria/reconnecting-websocket/blob/master/reconnecting-websocket.ts#L194 

```typescript
public onerror?: (event: Event) => void = undefined;
```

**Comment by pladaria** [comment]
Thanks for reporting, next version will fix it
