### ISSUE TITLE
How to use in browser client

### ISSUE THREAD

**Issue by realworld666** [pladaria/reconnecting-websocket#109]
I'm having the same issue as #55 
I want to use this client-side, not as part of a nodejs application. I can't find any instructions on how I do this or if it's even possible

**Comment by pladaria** [comment]
What have you tried?

How do you import libraries in your application?

**Comment by realworld666** [comment]
I tried putting the typescript file and the compiled js file in a js folder and using 
<script src="js/reconnecting-websocket.js"></script>
to include the compiled file. It complains about 
`Uncaught ReferenceError: exports is not defined`
If I hacky define exports like this
 <script>var exports = {};</script>
then one of my other dependencies falls over because it has some branching logic based on the existence of that variable.

**Comment by pladaria** [comment]
Use `reconnecting-websocket-iife.js`

Or import directly from a CDN:
```js
<script src="https://unpkg.com/reconnecting-websocket@4.2.0/dist/reconnecting-websocket-iife.js"></script>

<script>
var ws = new ReconnectingWebSocket('wss://echo.websocket.org/');
ws.onmessage = m => alert(m.data);
ws.send('hello world');
</script>
```
try [here](https://codepen.io/pladaria/pen/MWgvjrO)

**Comment by realworld666** [comment]
Thank you
