### ISSUE TITLE
[BROKEN]Main and module files specified in package.json are missing

### ISSUE THREAD

**Issue by rimzici** [pladaria/reconnecting-websocket#111]
```
"main": "./dist/reconnecting-websocket-cjs.js",
"module": "./dist/reconnecting-websocket-mjs.js",
"types": "./dist/reconnecting-websocket.d.ts",
```

Above files, specified in package.json are no more present.

I am not sure if it was intentional, but I could see this [commit](https://github.com/pladaria/reconnecting-websocket/commit/0cafe68314bd25c23e243b14bf5bbfac61fac09c) deletes the `dist` directory.

Please do review when you get time!

Thanks!

**Comment by pladaria** [comment]
`dist` folder is a build artifact and it is published in `npm` package

You can check it here:
https://unpkg.com/browse/reconnecting-websocket@4.3.0/
