### ISSUE TITLE
Cannot find name 'MessageEvent'

### ISSUE THREAD

**Issue by bennycode** [pladaria/reconnecting-websocket#131]
I changed the value for `lib` in my "tsconfig.json" from `["dom", "es2017"]` to `["es2017"]` because I am working on a Node.js-only project (no Browser environment). Unfortunately, this broke my integration with "reconnecting-websocket". I am getting now the following errors:

```
##[error]node_modules/reconnecting-websocket/dist/events.d.ts(20,14): error TS2304: Cannot find name 'MessageEvent'.
##[error]node_modules/reconnecting-websocket/dist/events.d.ts(30,22): error TS2304: Cannot find name 'MessageEvent'.
##[error]node_modules/reconnecting-websocket/dist/events.d.ts(31,30): error TS2304: Cannot find name 'MessageEvent'.
##[error]node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(24,54): error TS2304: Cannot find name 'Blob'.
##[error]node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(54,17): error TS2304: Cannot find name 'BinaryType'.
##[error]node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(96,25): error TS2304: Cannot find name 'MessageEvent'.
```

When digging into "reconnecting-websocket.ts", I realized that it expects "MessageEvent" to come from TypeScript's internal "DOM" library which is not available in a Node.js environment.

On Node.js the `MessageEvent` can be retrieved from the "ws" package:

```
import WebSocket, {MessageEvent} from 'ws';
```

Can this information be included in "reconnecting-websocket"?

**Comment by jwaldrip** [comment]
Affecting us as well on a react-native typescript project

**Comment by HouCoder** [comment]
Searched the whole repo, couldn't figure out where's the definition of `MessageEvent`.

**Comment by bennycode** [comment]
@HouCoder I figured out that [MessageEvent](https://developer.mozilla.org/docs/Web/API/MessageEvent) ships with TypeScript's dom library, so you have to add this in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": ["dom"],
    ...
  }
}
```

**Comment by HouCoder** [comment]
Thanks @bennyn for your quick response.

**Comment by coffeemug** [comment]
@jwaldrip -- have you guys figured out how to fix this in React Native? @bennycode's solution doesn't work in React Native-- it introduces hundreds of duplicate definition conflicts. Spent some time on this, still not sure how to get it working.

**Comment by bennycode** [comment]
Ideally, "reconnecting-websocket" would use "@types/ws" which has a definition for `WebSocket.MessageEvent`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/47e9cf6d8947e46a82bb09bbcc3dd74a3ac0ffa1/types/ws/index.d.ts#L188-L192

Unfortunately, "reconnecting-websocket" currently relies on the "dom" lib that ships with TypeScript. That's why you would have to write your own definition for `MessageEvent` if you like to use it with React Native.

**Example:**

```ts
declare global {
  interface MessageEvent {
    data: string;
    type: string;
  }
}
```
