### ISSUE TITLE
TypeError: Invalid WebSocket constructor. Set `options.constructor`

### ISSUE THREAD

**Issue by LeetCodes** [pladaria/reconnecting-websocket#17]
code doesnt work at all, just get this error 
TypeError: Invalid WebSocket constructor. Set `options.constructor`

tried running all examples, also tried to test but got errors with it, any help is appreciated

**Comment by LeetCodes** [comment]
`const WebSocket = require('reconnecting-websocket');
const ws = new WebSocket('ws://echo.websocket.org', null, {maxRetries: 3});

ws.addEventListener('open', () => {
    ws.send('hello!');
});
ws.onerror = (err) => {
        console.log(err);
};
`

**Comment by pladaria** [comment]
Where are you executing your code? Browser (using webpack/browserify) or node.js?

If you are using node.js, it fails because there's no global WebSocket in node. 

Have a look at the README or see how tests are implemented (using the module html5-websocket to wrap a ws)
