### ISSUE TITLE
Seems to be broken with API Gateway Websockets

### ISSUE THREAD

**Issue by mikhael28** [pladaria/reconnecting-websocket#178]
When using SAM (serverless application model, for AWS) to connect to the WebSocket that is provisioned by API Gateway, seems to fail for no good reason. The reason why I added this package initially was to reconnect after 10 minutes in case the websocket connection timed out (API gateway automatically timeouts) - however, i ended up manually adding a ping endpoint instead of this. This was constantly breaking the connection and reconnecting to the websocket, creating unnecessary connectionIds/etc.

Just leaving this as a note, in case anyone is also having problems with API Gateway provisioned websocket endpoints.

**Comment by ArtemZakharchuk** [comment]
Hi @mikhael28. API Gateway Websockets have Idle Connection Timeout - 10 minutes. After 10 minutes the idle WebSocket connection closes. You are cant reconnect to a closed connection. To prevent Connection from closing you need to send any data through it. https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#apigateway-execution-service-websocket-limits-table

**Comment by mikhael28** [comment]
Ahh yes, I implemented a `ping` to keep the connection alive. It seems I had the order of operations wrong/my conceptual understanding was wrong - I should have done that first, and then used websocket reconnect to try and reconnect if the connection closed/the device went offline. At some point in the future, I will add your library back potentially (though I might include my own logic when 'onlinereconnect' event listener (or whatever its called) fires, as I would need to fetch more than just the websocket data. Cheers, thank you for your reply! I hope it will help people :D
