### ISSUE TITLE
I cannot close a connection

### ISSUE THREAD

**Issue by paliuca** [pladaria/reconnecting-websocket#188]
I tried to close the currenct connection with no success. 
Ex: for a certain reason i need to close the connection, usual case (maxRetries: this.desktop ? Infinity : 3).
So if the retries are not finished it still reconecting event I am closing the connection manualy. (rws.close(3001, 'force')).
Thanks

**Comment by paliuca** [comment]
Solved.

**Comment by coolRoger** [comment]
> 

can you explain how to solved? i am facing the same issue
