### ISSUE TITLE
Change WebSocket connection URL during runtime

### ISSUE THREAD

**Issue by bennyn** [pladaria/reconnecting-websocket#20]
Our backend at [Wire](https://wire.com/) requires an access token as part of the WebSocket connection URL. 

The schema looks like this:

```
wss://prod-nginz-ssl.wire.com/await?access_token=Dp42wWHPiGukagf86Djx7JvVKed
```

The access token must be renewed at a certain interval which leads to problems when using `ReconnectingWebsocket` because it will still try to reconnect to the URL it has been initialized with (which could have an outdated `access_token`).

Is there a chance to change the connection URL at runtime? Telling from the [type definitions](https://github.com/pladaria/reconnecting-websocket/blob/v3.0.7/dist/index.d.ts) it doesn't look like it's accessible. 😢

**Comment by pladaria** [comment]
fixed in #4
