### ISSUE TITLE
receive a imcomplete message

### ISSUE THREAD

**Issue by eruca** [pladaria/reconnecting-websocket#22]
I use golang implement the websocke server and reconnecting-websocket in browser;the server log print the server send the complete message to the browser, but the browser only recevie imcomplete message.

```js

const ws = new ReconnectingWebSocket("ws://" + url, undefined, {debug: true});

    ws.onmessage = e => {
        if (typeof e.data === "string") {
            emitter(JSON.parse(e.data));
        } else {
            console.debug("[WebSocket] get data is not string, but", typeof e.data, "e:", e)
        }
    };
```

browser throw error of JSON.parse(), and the receive data is below:
```js
{"type":"FETCH_ASSESSMENTS_SUCCESSED","payload":{"n
```

**Comment by pladaria** [comment]
I guess this is a problem with your server.
Try to reproduce using the browser's WebSocket. `reconnecting-websocket` is just a thin layer over the native WebSocket.
