### ISSUE TITLE
Constructing ReconnectingWebsocket error in TypeScript

### ISSUE THREAD

**Issue by slikts** [pladaria/reconnecting-websocket#24]
Code: ```new ReconnectingWebSocket(url)```

Error: ```'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.'```

**Comment by pladaria** [comment]
Just published v3.2.0 with `noImplicitAny` set to `true`

**Comment by alex-weaver** [comment]
This still seems to be an issue in v3.2.0 and v3.2.1, unless there's a mistake in the import declaration? The code I'm using is as follows:

```
import ReconnectingWebSocket from 'reconnecting-websocket'
const socket = new ReconnectingWebSocket('ws://my.site.com');
```

This is using the npm package, imported using:
`"reconnecting-websocket": "3.2.1"`
(Also tried with 3.2.0)

This yields two errors:
```
TS2350	(TS) Only a void function can be called with the 'new' keyword.
TS7009	(TS) 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
```

Is there a mistake in how I'm importing the library?

**Comment by slikts** [comment]
> Is there a mistake in how I'm importing the library?

There isn't, it doesn't seem like the author would have tried actually using their code with TypeScript.

**Comment by pladaria** [comment]
Hi @alex-weaver,

Thanks for reporting. Should be fixed in v3.2.2

Don't hesitate to open a new ticket if you find any issue :)

**Comment by pladaria** [comment]
Although this lib was coded for js users in mind, here you have a working ts example:
```
import * as WS from 'html5-websocket';
import * as RWS from 'reconnecting-websocket';

const rws = new RWS('ws://echo.websocket.org/', undefined, {constructor: WS});

rws.onopen = () =>
    rws.send('hello');

rws.onmessage = (e) => {
    console.log(e.data);
    rws.close(0, 'bye', {keepClosed: true});
};
```

**Comment by planetrenner-martin** [comment]
I get an error message, when using `"strict": true` in the compiler options:

`test.ts`:
```
import * as ReconnectingWebsocket from 'reconnecting-websocket';

const websocket: WebSocket = new ReconnectingWebsocket('url', undefined, {constructor: WebSocket});
```

`tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "strict": true,
    "allowSyntheticDefaultImports": true
  }
}
```

Compile error:
```
node node_modules/typescript/lib/tsc.js -p tsconfig.json

test.ts(3,30): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
```
If I remove `"strict": true` from `tsconfig.json`, the code compiles fine. But I want this option to be `true`.

tsc: 2.4.2
reconnecting-websocket: 3.2.2

**Comment by fahdk** [comment]
Same error.
Typescript 2.7.2, reconnecting-websocket 3.2.2

```{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  }```

**Comment by kalmi** [comment]
My understanding is that changing noImplicitAny in the library's tsconfig will have no effect whatsoever when importing as only the importer project's tsconfig will be in effect.
