### ISSUE TITLE
"beforeReconnect" & "afterReconnect" callbacks

### ISSUE THREAD

**Issue by bennyn** [pladaria/reconnecting-websocket#28]
We have a use case where we need to execute a function before every WebSocket reconnect. It would be great if the `ReconnectingWebsocket` instance could execute a function (like `beforeReconnect`) on every reconnect.

Another option, to fulfill our needs, would be making use of `Promises` for `getUrl`. But this requires the `ReconnectingWebsocket` to wait for a `Promise` to resolve.

**Idea:**

```javascript
const getUrl = () => Promise.resolve('ws://echo.websocket.org/?id=something_special');
const rws = new ReconnectingWebSocket(getUrl);
```

**Comment by pladaria** [comment]
I like the idea of using a `Promise` for `getUrl`.

**Comment by hhamalai** [comment]
I've been trying to implement async flow here too, however registering event listeners in this current manner gets complicated requiring the event handlers to be passed into ReconnectingWebSocket as parameters.

**Comment by pladaria** [comment]
Latest version supports passing `() => Promise<string>` as url parameter
