### ISSUE TITLE
Failing test: level0 event listeners are reassigned after reconnect

### ISSUE THREAD

**Issue by bennyn** [pladaria/reconnecting-websocket#29]
I forked "reconnecting-websocket", did `npm install` and ran `npm test`. Unfortunately, the tests are failing on my machine (Windows 10, Node.js v8.4.0):

**Failing test:** level0 event listeners are reassigned after reconnect 
**Reason:** Planned for 26 assertions, but got 27.

**Screenshot:**

![Screenshot](https://user-images.githubusercontent.com/469989/30639728-553fd842-9e00-11e7-8ba6-cc4c10c56388.PNG)

**Comment by pladaria** [comment]
Works for me (linux box)

**Comment by pladaria** [comment]
I've upgraded some dependencies. Would you mind to try again. I've tested in Linux and Mac and works fine. Please re-open if this is still an issue for Windows and I will download a VM and investigate.

Thanks
