### ISSUE TITLE
use of cookie header

### ISSUE THREAD

**Issue by mschipperheyn** [pladaria/reconnecting-websocket#35]
I use Spring Websocket on the server side and the version I work with, basically uses a sessionid to get into the authenticated areas. Is there a way to add a header that gets sent with the connection attempt?

**Comment by pladaria** [comment]
JS WebSocket API has no method to send additional headers
https://html.spec.whatwg.org/multipage/web-sockets.html#network

This StackOverflow answer could be useful to you:
https://stackoverflow.com/a/4361358/1430450

**Comment by mschipperheyn** [comment]
Yeah, unfortunately, that doesn't work in my case. React-native has an undocumented option that you can pass with a cookie header.
