### ISSUE TITLE
Support passing a function as url to the constructor

### ISSUE THREAD

**Issue by pladaria** [pladaria/reconnecting-websocket#4]
This way the URL can easily change between reconnects

**Comment by oxygens** [comment]
More importantly, keeping track of websockets can be tedious. So, the same can be said about the keepClosed flag. It would be nice to have a keepClosedCallback.

Thinking further, it would be nice that the entire options should be like a callback. And it is:

Considering objects in JavaScript are passed by reference, wouldn't it be simpler to just modify the reference of the options parameter, and thus be able to modify any option?

Making the URL in the constructor a function is  incompatible with the standard and would make this entire library not swappable in certain scenarios.

It would be much better be able to specify the URL as an options attribute, AND for the reconnecting websocket to keep a reference to the options object.

**Comment by pladaria** [comment]
Ok, if someone has the need for it I will consider implementing that feature.

**Comment by bennyn** [comment]
@pladaria: A dynamic function to change the connection URL could help with [our use case](https://github.com/pladaria/reconnecting-websocket/issues/20). 🙂

**Comment by pladaria** [comment]
Sorry for the delay, I've been really busy those days. 

I hope this fits your needs :)
