### ISSUE TITLE
Webpack?

### ISSUE THREAD

**Issue by jfuehner** [pladaria/reconnecting-websocket#41]
How can I use this library with webpack? Using this doens't work...

`import ReconnectingWebsocket from 'reconnecting-websocket'`

**Comment by syuilo** [comment]
try:
``` javascript
const ReconnectingWebSocket = require('reconnecting-websocket');
```

**Comment by jfuehner** [comment]
Sorry, I should of been more clear. The _require_ syntax works with Webpack but, I want to use the _import_ syntax for this library.

`const ReconnectingWebSocket = require('reconnecting-websocket');` <-- this works

`import ReconnectingWebsocket from 'reconnecting-websocket' <-- this doesn't

**Comment by syuilo** [comment]
Hmm, another idea came up:
``` javascript
import * as ReconnectingWebsocket from 'reconnecting-websocket';
```

**Comment by syuilo** [comment]
or
``` javascript
import ReconnectingWebsocket = require('reconnecting-websocket');
```

**Comment by jfuehner** [comment]
Hmm... Doing this, `import * as ReconnectingWebsocket from 'reconnecting-websocket'` ReconnectingWebsocket comes back as undefined.

**Comment by syuilo** [comment]
I cannnot reproduce it...
`import * as ReconnectingWebsocket from 'reconnecting-websocket';` is works well.
Make sure there are no misspellings (eg 's' is not uppercase 'S')

**Comment by jfuehner** [comment]
Was there perhaps something you had to configure in your webpack config to get the import syntax to work?

**Comment by syuilo** [comment]
I think that there is no setting.
Just to be sure, can you tell me the version of your webpack?

**Comment by pladaria** [comment]
@jfuehner are you importing the library into javascript or typescript?

**Comment by jfuehner** [comment]
@pladaria I'm importing into javascript using webpack v2.6.1

**Comment by pladaria** [comment]
@jfuehner we are using this module with webpack since webpack 1.x without any issues. Please, create a repo with the steps to reproduce and then feel free to reopen this issue.
