### ISSUE TITLE
Typescript defs for close are missing third argument

### ISSUE THREAD

**Issue by bvandenbos** [pladaria/reconnecting-websocket#44]
`ReconnectingWebsocket` extends `WebSocket` but doesn't redefine the `close` method to take the third "options" parameter.

Closing a reconnecting websocket like this:

```
rws.close(1000, '', opts);
```

Results in a typescript error; `Expected 0-2 arguments, but got 3`.

**Comment by bennyn** [comment]
I got the same issue with reconnecting-websocket v3.2.2:

![unbenannt](https://user-images.githubusercontent.com/469989/33934694-f71e935c-dff9-11e7-9933-40fd641d0d40.PNG)

Here is my code:

```typescript
const Html5WebSocket = require('html5-websocket');
const ReconnectingWebsocket = require('reconnecting-websocket');

private socket: WebSocket;

// ...

public connect(clientId?: string): void { 
  this.socket = new ReconnectingWebsocket(...);
}

public disconnect(): void {
  // TS2554: Expected 0-2 arguments, but got 3.
  this.socket.close(1000, '', {keepClosed: true, fastClose: true, delay: 0});
}
```

Luckily there is a workaround:

```typescript
public disconnect(): void {
  const socket: any = this.socket; // Cast 'WebSocket' into 'any' in order to supply a third parameter
  this.socket.close(1000, '', {keepClosed: true, fastClose: true, delay: 0});
}
```

**Comment by bennyn** [comment]
Any update on this?

**Comment by pladaria** [comment]
Should be fixed in latest release. Thanks

**Comment by bennyn** [comment]
@pladaria Can you provide an example on how to use this library with TypeScript? I tried to use it but it has some problems.

Here is my code:

```ts
import ReconnectingWebsocket = require("reconnecting-websocket");

const socket = new ReconnectingWebsocket(
  () => this.buildWebSocketURL(),
  undefined,
  WebSocketClient.RECONNECTING_OPTIONS
);
```

It thows the following error:

![image](https://user-images.githubusercontent.com/469989/40783925-436dfdb4-64e4-11e8-90f6-f8c7bd0e6366.png)

**Comment by pladaria** [comment]
Hi,

Thanks for checking the new library version! 

* Update to latest version (4.0.0-rc5 while writing this) 
* Compile with `esModuleInterop` enabled and use ES imports, this small node script works for me:

```javascript
import ReconnectingWebsocket from 'reconnecting-websocket';
import WebSocket from 'ws';

const getUrl = () => Promise.resolve('ws://echo.websocket.org/');
const OPTIONS = {WebSocket};

const rws = new ReconnectingWebsocket(getUrl, undefined, OPTIONS);

rws.addEventListener('open', () => {
    rws.send('hi');
});

rws.addEventListener('message', (event) => {
    console.log(event.data); // prints "hi"
});
```

Please don't hesitate to open an issue if you find any problem

**Comment by bennyn** [comment]
@pladaria I checked the ["close" function of v4.2.0](https://github.com/pladaria/reconnecting-websocket/blob/v4.2.0/reconnecting-websocket.ts#L224-L237) and it is defined to accept only 2 parameters ("code" and "reason"), so I guess there is no more support for a third ("options") parameter?
