### ISSUE TITLE
Expose retriesCount ?

### ISSUE THREAD

**Issue by wd** [pladaria/reconnecting-websocket#53]
Will you consider to expose `retriesCount` to user ?  So that users can show this count somewhere.

**Comment by wd** [comment]
I agree, or maybe you can add both. Thanks.

**Comment by pladaria** [comment]
Exposed `retryCount` in latest version. Thanks

**Comment by wd** [comment]
```
        this._uptimeTimeout = setTimeout(()=>this._acceptOpen(), minUptime);
```
Here should be used an arrow function, otherwise `this` in `_acceptOpen` will be undefined.

```
Cannot set property '_retryCount' of undefined
_acceptOpen    reconnecting-websocket-cjs.js:301:8<unknown>
 ```
