### ISSUE TITLE
What if no on-close event is triggered?

### ISSUE THREAD

**Issue by amanjaggaPracto** [pladaria/reconnecting-websocket#54]
If no on-close event is triggered  and this can happen due to situations like network failures etc.
Do you handle these scenario's for reconnecting?

**Comment by pladaria** [comment]
That should be handled by the underlying WebSocket.

Normally, in the application layer, a ping mechanism should be implemented (like in the xmpp protocol) if a ping timeouts, you can call `reconnect` method to restart the connection.
