### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by jiajunxiong** [pladaria/reconnecting-websocket#58]
> npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> reconnecting-websocket@3.2.2 prepublish C:\projects\reconnecting-websocket\reconnecting-websocket
> npm run clean && npm run build && npm run build-amd && npm test

> reconnecting-websocket@3.2.2 clean C:\projects\reconnecting-websocket\reconnecting-websocket
> rimraf dist

> reconnecting-websocket@3.2.2 build C:\projects\reconnecting-websocket\reconnecting-websocket
> tsc

> reconnecting-websocket@3.2.2 build-amd C:\projects\reconnecting-websocket\reconnecting-websocket
> tsc -m AMD --outFile ./dist/reconnecting-websocket.amd.js

> reconnecting-websocket@3.2.2 test C:\projects\reconnecting-websocket\reconnecting-websocket
> nyc --reporter=text-summary --reporter=lcov ava --verbose --serial test/test.js

  √ throws with invalid constructor
  √ throws if not created with `new`
  √ global WebSocket is used if available (1s)
  √ url provider
  √ connection status constants
  √ max retries (3s)
  × level0 event listeners are reassigned after reconnect Planned for 26 assertions, but got 27.
  √ level0 event listeners are reassigned after closing with fastClose (166ms)
  √ level2 event listeners (addEventListener, removeEventListener) (4s)
  - connection timeout
  √ connect, send, receive, close {fastClose: false}
  √ connect, send, receive, close {fastClose: true}
  √ close and keepClosed (107ms)
  √ debug mode logs stuff (1s)
  √ #14 fix - closing with keepClose before open (1s)

  1 test failed [10:10:03]
  1 test skipped

  level0 event listeners are reassigned after reconnect

  C:\projects\reconnecting-websocket\reconnecting-websocket\test\test.js:90

   89:
   90:     t.plan(26); // 5 ECONNREFUSED + 1 EHOSTDOWN + 5 * 4 t.is()
   91:     const handleOpen = () => {};

  Planned for 26 assertions, but got 27.

=============================== Coverage summary ===============================

Statements   : 100% ( 145/145 )
Branches     : 100% ( 64/64 )
Functions    : 100% ( 31/31 )
Lines        : 100% ( 132/132 )
================================================================================

npm ERR! Test failed.  See above for more details.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reconnecting-websocket@3.2.2 prepublish: `npm run clean && npm run build && npm run build-amd && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reconnecting-websocket@3.2.2 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jiajun.xiong\AppData\Roaming\npm-cache\_logs\2018-05-08T02_10_03_996Z-debug.log

**Comment by pladaria** [comment]
Feel free to submit a PR

**Comment by pladaria** [comment]
Hi, I've just released a major version of the library. It's a full rewrite and many bugs have been fixed.

Please, if you still reproduce the problem, reopen the ticket.
