### ISSUE TITLE
Cannot send messages using `reconnecting-websocket` (works with vanilla `WebSocket`)

### ISSUE THREAD

**Issue by Iambecomeroot** [pladaria/reconnecting-websocket#66]
I am so lost. I cannot send messages using this library. Using the browser's `WebSocket` (as can be seen in the minimal example below), works fine. I am using a simple server configuration to echo all messages received using https://www.npmjs.com/package/ws. 
```js
const ws = new ReconnectingWebSocket(`ws://${location.hostname}:5000`)

ws.onopen = () => {
  ws.send('test')
}
// Gives 'test' in node.js console
```

```js
const ws = new WebSocket(`ws://${location.hostname}:5000`)

ws.onopen = () => {
  ws.send('test')
}
// Nothing in node.js console
```

I have read through the code and I have no clue why this would be happening. You don't appear to be doing anything fancy with `ws.send`. Any suggestions?

**Comment by pladaria** [comment]
I can't reproduce your problem:

Here you have a simple example of `reconnecting-websocket` sending a message to an echo WebSocket server and printing the response:

https://codesandbox.io/s/3qj71v8m4m

Could you create a minimar repository where your issue is reproduced?

Thanks!

**Comment by Iambecomeroot** [comment]
Interesting. I tried it again (just replaced `WebSocket` with `ReconnectingWebSocket`) and everything is working perfectly. Maybe it was fixed in an update? Anyway, thanks for the response and for the project. Great stuff!
