### ISSUE TITLE
send() succeeds silently when underlying websocket is not initialized yet

### ISSUE THREAD

**Issue by haizz** [pladaria/reconnecting-websocket#67]
https://github.com/pladaria/reconnecting-websocket/blob/9b3eaee429253eb92d0f7e6aec38ac953ef681a3/reconnecting-websocket.ts#L220

```typescript
    /**
     * Enqueues the specified data to be transmitted to the server over the WebSocket connection
     */
    public send(data: string | ArrayBuffer | Blob | ArrayBufferView) {
        if (this._ws) {
            this._ws.send(data);
        }
    }
```

Result: message is lost, but application code thinks everything is OK.

Real-life example of such occurrence:

```typescript
const socket = new ReconnectingWebSocket(url);
// The main thread continues execution before ReconnectingWebSocket._ws is initialized.
// Maybe because of setTimeout() and Promises in ReconnectingWebSocket._connect logic?
socket.send("MSG");
// No exceptions, all send() calls are lost before _ws is initialized
```

**Comment by haizz** [comment]
I'm sorry, but because of this and #60 there is no way this supposedly very useful library is suited for any dependable production usage.

**Comment by pladaria** [comment]
Hi, sorry for the inconveniences. This and the other issue should be fixed in next release.

Thanks for reporting!
