### ISSUE TITLE
Disable reconnect after creating instance

### ISSUE THREAD

**Issue by TimPietrusky** [pladaria/reconnecting-websocket#70]
I wonder how I can disable the reconnect after I created an instance of ReconnectingWebSocket. What I tried is using `close`, but it's still trying to reconnect:

```js
let connection = new ReconnectingWebSocket('ws://localhost:3000');
connection.close();
```

## Version
* reconnecting-websocket: 4.0.0-rc5

**Comment by wd** [comment]
```
rws.close(1000, 'user logout', {keepClosed: true, fastClose: true});
```

**Comment by pladaria** [comment]
Thanks for reporting, will be fixed in next release
