### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by ftier-tech** [pladaria/reconnecting-websocket#71]
First, let me say what a great library.  It has been a blessing to use it.  Unfortunately, I had to upgrade to 4.0.0-rc5 from 3.2.2 that solved an issue, but when doing a react-scripts build, I get an error as follows:  
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/reconnecting-websocket/dist/reconnecting-websocket.mjs:1 

I've encountered this once before with another library and I just had to import an ES5 compliant version.  Was wondering what I need to do for this library.

Thank you!

**Comment by wd** [comment]
Same here, no './node_modules/reconnecting-websocket/dist' directory indeed.

**Comment by pladaria** [comment]
Next version will target ES5 so you shouldn't have these problems
