### ISSUE TITLE
No valid WebSocket class provided

### ISSUE THREAD

**Issue by SuperXFan** [pladaria/reconnecting-websocket#72]
in nodejs
const ReconnectingWebSocket = require('reconnecting-websocket');
let ws = new ReconnectingWebSocket('ws://192.168.90.124:3002/ws');

then
Error: No valid WebSocket class provided

**Comment by PierBover** [comment]
I'm getting this error on iOS 9, which AFAIK supports WebSocket since iOS 6.

https://caniuse.com/#search=websocket

**Comment by pladaria** [comment]
Please check with latest version, if the issue persists, please open a new issue
