### ISSUE TITLE
Option to not reconnect when server closes connection

### ISSUE THREAD

**Issue by masad-frost** [pladaria/reconnecting-websocket#78]
In the initial release of v4 close events coming from server did not trigger a reconnect. Which meant I was able to reconnect conditionally. My use case is that if a disconnect happens for a specific `reason` I don't want the client to retry. I can handle reconnection myself by calling `reconnect`.

**Comment by pladaria** [comment]
Hi, 

Thanks for reporting. You can do that using latest version of the lib:

```js
rws.addEventListener('close', e => {
    if (e.code === SOME_CODE) { // you could also check the reason
        rws.close(); // this keep closed and stop trying to reconnect
    }
});
```
