### ISSUE TITLE
How to set protocol

### ISSUE THREAD

**Issue by vincent714** [pladaria/reconnecting-websocket#9]
I set up the new object as follows,

```
var options = {connectionTimeout: 1000};
var reconnectingWebSocket = new ReconnectingWebsocket('wss://localhost:9090', null, options);

```

but in the Chrome console, it showed:

Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

I don't have any idea to fix it. Can someone help me? Thanks.

**Comment by pladaria** [comment]
Do you have the same issue using a regular WebSocket?

**Comment by dubiousdavid** [comment]
I'm having the same issue. Actually here is a pretty small test case:

```javascript
import WebSocket from 'reconnecting-websocket'
let ws = new WebSocket('wss://echo.websocket.org', null)
```

**Comment by pladaria** [comment]
According to the spec, the second argument must be a string or an array of strings:
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

If you don't want to set it, use undefined

Test here:
http://requirebin.com/?gist=d5d5e8aa7a31de1a4e4810a055c6c46d
