### ISSUE TITLE
ReconnectingWebSocket much slower than WebSocket

### ISSUE THREAD

**Issue by physicsai** [pladaria/reconnecting-websocket#91]
I have a simple app for asynchronous message passing, using websockets (React + Django). 

If I use `WebSocket`, the connection opens almost instantaneously upon loading the page, whereas if I switch to `ReconnectingWebSocket` (that's the only change in the code and using 
`import ReconnectingWebSocket from 'reconnecting-websocket';`
),  it takes around 3-5 seconds. 

Is the reason behind this delay understood?

**Comment by pladaria** [comment]
Hi, you can change `minReconnectionDelay`.

**Comment by physicsai** [comment]
Thank you, @pladaria. `ReconnectingWebSocket ` now also connects instantaneously.

**Comment by curran** [comment]
Yes please! Happy to come across this issue. Thanks for your work on this module!

**Comment by quentinus95** [comment]
@pladaria any idea on when you could fix this?

**Comment by naggie** [comment]
Wow thanks, this option has made my application go from being slow to instant!

I was relying on the reconnect method combined with a URL function to change the URL without reassociating handler.

**Comment by naggie** [comment]
I suggest that calling the reconnect() method should reconnect immediately (like the initial connection) as it's an explicit action. The automatic reconnects should still be throttled.

**Comment by Fxlr8** [comment]
Almost a year passed and a huge delay before the first connection is still here. Why is this the default behavior? I can't imagine a single use case where this will not ruin the user experience. C'mon the lib is nice, just fix this issue finally please

**Comment by curran** [comment]
The fix has been sitting in this open PR since Nov 2018 https://github.com/pladaria/reconnecting-websocket/pull/94 . It appears @pladaria is not maintaining the lib anymore.

Does anyone know of an active fork of this project? I think that's what's neede to actually solve this, unfortunately.

**Comment by pladaria** [comment]
Fixed in #94
